### PR TITLE
Fixes warnings for unused datavars and addons

### PR DESCRIPTION
**Pull request by bartvanerp**
Hi @Chengfeng-Jia, I made a start with #104. I think it has mostly been resolved, but it lacks tests. If @bvdmitri agrees with the solution approach, we can start writing those.

@bvdmitri Is the proposed solution okay? I added the warn argument also in the `ModelOptions` struct, such that we can use this upon model creation.

### CODE REVIEW

**Comment by bartvanerp** [comment]
ping @bvdmitri :)

**Comment by bvdmitri** [comment]
@bartvanerp Solution approach is good! I've changed some minor stuff, simple tests would be nice

**Comment by bartvanerp** [comment]
Thanks @bvdmitri! @Chengfeng-Jia would you be available to test the functionality?

**Comment by Chengfeng-Jia** [comment]
I will write some tests for that.

**Comment by Chengfeng-Jia** [comment]
Hi, guys, I wrote some tests for this improvement. However, I added some new models to the existing test code. If you think it's unnecessary please let me know.

**Comment by bartvanerp** [comment]
Thanks @Chengfeng-Jia! In my opinion the tests look good. I moved everything to `test_inference.jl`, as we are specifically testing the `inference()` function, but aside from that, excellent job! @bvdmitri ready for review

**Review by bvdmitri — APPROVED** [review]

**Pull request merged**
