### PR TITLE
Update Hierarchical BLR

### PR DESCRIPTION
**Pull request by albertpod**
This PR fixes minor mistakes with Hierarchical Bayesian Linear Regression that we found following the discussion #199

### CODE REVIEW

**Comment by bartvanerp** [comment]
It seems that the updated notebooks failed to execute as it does not know the `infer` function. I guess this has something to do with the versioning

**Review by bartvanerp — CHANGES_REQUESTED** [review]
It seems that the updated notebooks failed to execute as it does not know the infer function. I guess this has something to do with the versioning

**Comment by albertpod** [comment]
@bartvanerp, perhaps that's because the new version of `RxInfer.jl` hasn't been released; examples look into the released version.

**Comment by albertpod** [comment]
@bartvanerp I see that tests for examples pass in CI.

**Comment by bartvanerp** [comment]
Hmm that's strange, in the notebook viewer it says that some cells failed. I don't think this reruns the code.

**Comment by albertpod** [comment]
Not sure why it happens then. It went well here https://github.com/biaslab/RxInfer.jl/pull/190

**Review by bartvanerp — APPROVED** [review]

**Pull request merged**
