### PR TITLE
change to scatter plot

### PR DESCRIPTION
**Pull request by cscherrer**
This small PR changes the plot in `Linear Regression.ipynb` to a scatterplot. This is a much more common way to present input data for a simple regression model, and will be more familiar to most users.

### CODE REVIEW

**Comment by bvdmitri** [comment]
Thanks @cscherrer ! I have updated a bit the demo itself, could you please take a look on the updated version? I also want to add a multivariate regression (as from here https://discourse.julialang.org/t/reactivemp-how-to-run-linear-model-with-multiple-predictors-and-an-intercept/85290/6), but didn't have time yet.

**Comment by bvdmitri** [comment]
UPD: I have added the multivariate example as well.

**Comment by bvdmitri** [comment]
Hey @cscherrer , did you have time to check the updated version?

**Comment by bvdmitri** [comment]
<p>Good point!</p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
<p>Double checked in the notebook, renders correctly. It must be an issue with the <code>reviewnb</code>.</p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cscherrer** [comment]
<h2><a href="https://emojis.wiki/thumbs-up/" target="_blank">👍</a></h2>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cscherrer** [comment]
<p>Ok, then it would be very helpful to have some documentation about this. Otherwise, users are very likely to think this is the standard way of doing things in RxInfer. Very few will recognize it as a CI quirk.</p><p> </p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
<p>The code in this cell has nothing to do with RxInfer, its just plotting. I also wouldn't call it a CI quirk, the <code>global</code> keyword is a standard documented way in Julia to override a global variable in a local scope (which is what happening exactly). It also backward compatible with older versions of Julia and older version of REPL for example, so I'm not really sure if it is an issue at all. </p><p> </p><p>I'm also not sure if users will first read the whole documentation to find a small note about this and only then see the examples. </p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
<blockquote>Is it different from&nbsp;<code>I</code>?</blockquote><p>Yes, it returns a <code>Matrix</code>.</p><p> </p><blockquote>With no comment I think users are likely to be confused</blockquote><p>Well, why wouldn't users to have the exactly same feelings about <code>I</code>, (1) where is this defined and (2) if we use <code>I</code> does it mean that other methods won't work in this context, (3) how its different from <code>Diagonal(ones(m))</code> etc.. </p><p> </p><p>I think there are like 10+ times to define a diagonal matrix in Julia and I do think that any of those should work in this context. <code>diageye(m)</code> is one way, we could use another. For me personally it does not matter at all, but we can change of course. </p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cscherrer** [comment]
<p>Right, sorry I lost context when writing that last comment. I agree it's not really an issue.</p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
<p>We don't have the documentation for the <code>diageye</code> though, so it might be worth to add it. </p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cscherrer** [comment]
<blockquote>Well, why wouldn't users to have the exactly same feelings about <code>I</code>, (1) where is this defined and (2) if we use <code>I</code> does it mean that other methods won't work in this context, (3) how its different from <code>Diagonal(ones(m))</code> etc..</blockquote><p> </p><p>All of these are defined in Julia standard libraries, and are very well-known. I don't think anyone could reasonably expect you to document uses of such standard functions unless you're writing something for very new-to-Julia users, or using things in very unusual ways.</p><p> </p><p>But if <code>diageye</code> is defined in ReactiveMP and these examples are intended as a tutorial on that, then I wouldn't expect users to be familiar with that function.</p><p> </p><p>I think a comment like </p><p><code># ReactiveMP.diageye(n) == collect(I(n))</code></p><p> </p><p>would do the trick, though for me there's a second question of why you would prefer this, given the extra allocation cost. Maybe ReactiveMP requires <code>Arrays</code>s instead of <code>AbstractArray</code>s? In that case I think it would be important to document that.      </p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
<blockquote>All of these are defined in Julia standard libraries, and are very well-known.</blockquote><p>Ok, you are probably right, as I mentioned I don't mind changing this.</p><blockquote>though for me there's a second question of why you would prefer this, given the extra allocation cost.. </blockquote><p>It won't really save much in this example, the covariance of the posterior will be a full matrix in any case.</p><blockquote>&nbsp;Maybe ReactiveMP requires&nbsp;<code>Arrays</code>s instead of&nbsp;<code>AbstractArray</code>s?</blockquote><p>No, it does not.</p>

---

 <a href='https://app.reviewnb.com/biaslab/RxInfer.jl/pull/22/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bvdmitri** [comment]
Added in the https://github.com/biaslab/RxInfer.jl/commit/15924aa10de9cd29dbba0973afa23b8490607041. @cscherrer thanks for the comments!

**Pull request closed without merging**
